### ISSUE TITLE
Requesting support for EPSON ET-2550 Model

### ISSUE THREAD

**Issue by hj2650** [Zedeldi/epson-printer-snmp#2]
Hello,

Could you please add a support for model ET-2550? I have attached the wicreset log.
[application.log](https://github.com/Zedeldi/epson-printer-snmp/files/12787885/application.log)

Thank you very much.

**Comment by Zedeldi** [comment]
Hey,

As far as I'm aware, [`easysnmp`](https://pypi.org/project/easysnmp/) – which relies on [`net-snmp`](http://www.net-snmp.org/) – only supports IPv4/IPv6 rather than USB connections.

However, the Epson EcoTank ET-2550 appears to support Wi-Fi connectivity, so it should be able to grab an IP address to use for SNMP.

It should also be possible to obtain the correct OIDs from the `wicreset` log, but I'm away for the next few days. I'm happy to have a look when I get back. Did the waste ink counters get reset successfully, or does it still show the initial values?

Thanks,
Zack

**Comment by hj2650** [comment]
> It should also be possible to obtain the correct OIDs from the `wicreset` log, but I'm away for the next few days. I'm happy to have a look when I get back. Did the waste ink counters get reset successfully, or does it still show the initial values?

It was successfully reset to 20%. Thank you very much!
